### ISSUE TITLE
Portable app on Windows

### ISSUE THREAD

**Issue by Bonnev** [TomoyukiAota/photo-location-map#546]
### Version of Photo Location Map

1.9.0

### OS

Windows

### OS Version

11

### Description

Could we make the app portable? I would like to use the app without an installer.

**Comment by TomoyukiAota** [comment]
@Bonnev 
I did quick Google search and it seems it's technically possible. I'll consider working on this sometime.

**Comment by TomoyukiAota** [comment]
I tried creating the portable app on Windows.
It turned out there are several problems.

1. It takes long time (30-40 seconds) to launch the portable app on my PC. Note that it takes only 4-5 seconds to launch the installer version. Such a long launch time for the portable app is inevitable because the portable app needs decompressing the files to some temporary folder for each time the app launches.
2. After changing date & time format settings, the dialog to restart the app appears. Clicking OK closes the app, but the app does not start again. This can be reproduced by repeating "changing settings" and "clicking OK on the restart dialog" for 2 times in a row.
3. There are cases that the application window appears, but the window content is only the text "Loading...". This seems to happen when clicking OK on the restart dialog for setting changes for the very first time starting the portable app's executable.

Also, there seems to be an issue about carrying the portable app's settings to a different PC due to the fact that the settings are stored in %APPDATA%, not the location next to the portable app's executable.
https://github.com/electron-userland/electron-builder/issues/6473

There are too many problems which made me hesitant to officially support the portable version.
The code changes to make the portable app available is pushed to [experiment/portable-app-on-windows](https://github.com/TomoyukiAota/photo-location-map/tree/experiment/portable-app-on-windows) branch, so further experiments can be done in the future if the situation changes.
For now, I don't plan to support the portable app on Windows.

**Comment by JohnTHaller** [comment]
I stumbled across this in a GitHub search. I've packaged a base portable version in PortableApps.com Format in case there's interest from the developer here: https://portableapps.com/node/79174

This release moves the Photo Location Map folder to/from %APPDATA%. The full app is already extracted so it doesn't have a launch lag. Electron's built in 'portable' mode is more like a single EXE package. It's not portable, it just doesn't require an install.

If there is a command line option to direct to a different location for the app itself, we can use that to avoid the move back and forth. Examples in other Electron apps are Joplin which uses --profile "X:\Full\Path" and Whalebird which uses --user-data-dir="X:\Full\Path". We package these up as PortableApps.com releases.

You can package and release it yourself or I can help. The launcher and installer are both open source under the GPL.
